config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get '/about' => 'pages#about'

  resources :blog, only: :index

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  layout 'blog_layout'

  def index
    query_string = request.query_string

    if query_string.empty?
      render :index
    else
      @disqus = true
      @return_link = true
      post = (query_string.match /post=(\w+)/).captures[0]
      lang = (query_string.match /lang=(\w+)/).captures[0]
      render "blog/#{lang}/#{post}"
    end
  end



  def blah=(value)
    @blah = value
  end

  def blah
    @blah
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

  def music
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.haml
.row
  .col-md-12
    %h3 JavaScript Snippets
    %br
    %ul
      %li= link_to 'Delegator Pattern', blog_index_path(lang: 'js', post: 'delegate')
      %li= link_to 'Spies for Testing', blog_index_path(lang: 'js', post: 'spy')
      %li= link_to 'Functional Programming', blog_index_path(lang: 'js', post: 'functional_programming')
%br
.row
  .col-md-12
    %h3 Ruby Snippets
    %br
    %ul
      %li= link_to 'Delegator Pattern', blog_index_path(lang: 'ruby', post: 'delegate')
      %li= link_to 'Observer Pattern', blog_index_path(lang: 'ruby', post: 'publisher_subscribe')
      %li= link_to 'Getters and Setters', blog_index_path(lang: 'ruby', post: 'getters_and_setters')
%hr
.row
  .col-md-12
    %span.disclaimer Disclaimer: &nbsp;
    This code isn't particularly groundbreaking, but I'd like to keep a reference to things I've experimented with.

app/views/blog/js/bind.html.haml
.row
  .col-md-12
    %h4 How does JavaScript's "bind" work?
    %p First off, what is it used for?  When JavaScript an event handler is invoked on an object, the value of 'this' is not set to the object the method belongs to; rather the DOM element is the value of 'this'.  If we want the method to permanently be stuck to its object, we can use bind.  See below:
    :coderay
      #!javascript

      var my_object = {
        respondToSomething: function () {
          this.sayHi();
        },

        sayHi: function () {
          alert('Hi');
        }
      }

      my_object.bind

app/views/blog/js/delegate.html.haml
.row
  .col-md-12
    %h4 Delegator Pattern
    %p I've found many times where I was writing methods that simply passed along the method/arguments to another object.  Once I had done this 3, 4 times, it started to clutter up the code for the original object.  The code below takes a list of methods and an object to forward them along to, and then writes the methods automatically.

    :coderay
      #!javascript

      // note: I don't ever modify Object's prototype directly in my codebase

      Object.prototype.delegate = function (methods, opts) {
        var self = this;  // save a reference to the object doing the delegating

        if (_.isString(methods)) { methods = [methods]; } // normalize methods to array

        _.each(methods, function (method) {
          // dynamically create a method that passes the arguments along to the receiver's method of same name
          self[method] = function () {
            var receiver = self[opts.to];
            return receiver[method].apply(receiver, arguments);
          };
        });
      };

      // simple usage example...
      var musicBox = {
        hendrix: {
          playGuitar: function () { console.log('twanggggg'); }
        }
      }

      musicBox.delegate('playGuitar', { to: 'hendrix' });
      musicBox.playGuitar();  //  console:  twanggggg

app/views/blog/js/delegator.html.haml
.row
  .col-md-12
    %h4 Delegator Pattern
    %p At work, we had several objects that received a method call and passed that message to one of the objects it was the owner of. Instead of having these custom methods, I wrote a delegator to write those methods automatically.

    :coderay
      #!javascript

      Object.prototype.delegate = function (methods, opts) {
        var self = this;
        if (_.isString(methods)) { methods = [methods]; }

        _.each(methods, function (method) {
          self[method] = function () {
            var receiver = self[opts.to];
            return receiver[method].apply(receiver, arguments);
          };
        });
      };

      // simple usage example...
      var musicBox = {
        hendrix: {
          playGuitar: function () { console.log('twanggggg'); }
        }
      }

      musicBox.delegate('playGuitar', { to: 'hendrix' });
      musicBox.playGuitar();  //  console:  twanggggg

app/views/blog/js/functional_programming.html.haml
.row
  .col-md-12
    %h4 Functional Programming in JavaScript
    %p Over time, I found myself using more and more functional programming techniques to accomplish tasks on our back end at ChalkSchools.  It was a natural next step to apply these techniques on the front end as well.  Even though various libraries provide functional capabilities, I did find that implementing the functions on my own helped bake the knowledge into my brain.  These do NOT reflect how either Underscore or Low-Dash implement the functions; rather, I illustrate one possible (and probably naive) implementation.  I am not worrying about browser inconsistencies, speed, or anything other than versions that just so happen to work in the Chrome browser I am currently on.
    %h5 _.map
    %p <b>Map</b> is a really simple concept: return a new array that has applied some transformation on each element in the source array.
    :coderay
      #!javascript

      var _ = {};

      _.map = function (array, func) {
        var output = [];

        for (var i = 0; i < array.length; i++) {
          output[i] = func(array[i], i);
        }

        return output;
      };

    %p Usage example:
    :coderay
      #!javascript

      var test_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
      var new_array = _.map(test_array, function (item, index) {
        return item * 2;
      });

      // new_array is now [2, 4, 6, ..., 20]
    %br
    %h5 _.each
    %p <b>Each</b> is similar to <b>map</b>, with the exception that it doesn't return anything other than undefined...  It is useful for modifying other variables that are within the same scope.
    :coderay
      #!javascript

      _.each = function (array, func) {
        for (var i = 0; i < array.length; i++) {
          func(array[i], i);
        }
      };
    %p Usage example:
    :coderay
      #!javascript

      var bunchOfThings = {};
      var test_array = ['a', 'b', 'c', 'd'];

      _.each(test_array, function (item, index) {
        bunchOfThings['item_' + index] = item;
      });

      // bunchOfThings now looks like this:
      {
        item_1: 'a',
        item_2: 'b',
        item_3: 'c',
        item_4: 'd'
      }
    %br
    %h5 _.reduce
    %p The last example I will run through here is the reduce function.  The idea behind this function is simple: pass in array and an aggregator function, and boil the array down to a single result value.  Here is my take:
    :coderay
      #!javascript

      _.reduce = function (array, func, memo) {
        for (var i = 0; i < array.length; i++) {
          memo = func(array[i], memo);
        }

        return memo;
      };
    %p Usage example:
    :coderay
      #!javascript

      _.reduce(
        [1,2,3],
        function (num, memo) { return num + memo; },
        10
      );
      // returns the value 16: 10 + 1 + 2 + 3

      _.reduce(
        ['a', 'cat.'],
        function (word, memo) { return memo + ' ' + word; },
        'I am'
      );
      // returns 'I am a cat.'

app/views/blog/js/spy.html.haml
.row
  .col-md-12
    %h4 Spies (Proxies) in JavaScript
    %p Nothing too exciting here, but I've noticed testing frameworks in Ruby and JavaScript making use of spies.  I created a very simple implementation just to make sure I understand how they work.
    :coderay
      #!javascript

      var Spy = function (source, func) {
        var self = this;
        self.called = false;

        var old_func = source[func];
        var new_func = function () {
          old_func.apply(source, arguments);
          self.called = true;
        }

        source[func] = new_func;
      }

      var blah = {
        old: function () { }
      }

      var spy = new Spy(blah, 'old');
      console.log('called before?', spy.called);  // false
      blah.old();
      console.log('called after?', spy.called);   // true

      'Cool!';

app/views/blog/ruby/delegate.html.haml
.row
  .col-md-12
    %h4 Delegator Pattern
    %p After using the delegator pattern with my Rails apps, I was curious how it might be implemented.  This is a very basic approach to it - literally just passing along the same arguments to the owned object without checking to make sure the object exists or doing anything fancy.
    :coderay
      #!ruby

      class Object

        def self.delegate(*args)
          to = args.pop[:to].to_s

          method_definitions = args.map do |meth|
            string_meth = meth.to_s
            " \
              def \#{string_meth}(*args) \
                \#{to}.\#{string_meth}(*args) \
              end \
            "
          end
          class_eval(method_definitions.join(';'))
        end

      end
    %br
    %p This is a <i>very</i> basic approach to delegation, as I didn't provide any nice features like prefixes on delegated methods.  These come in handy when both the object and one of the objects that you delegate to have a method with the same name.
    %p Continuing along, I'll show a simple example of actually using the delegator shown above:
    %br
    :coderay
      #!ruby

      class Cat
        def purr
          puts 'purr'
        end

        def meow
          puts 'meow'
        end
      end

      class CatOwner
        attr_accessor :cat

        delegate :purr, :meow, to: :cat

        def initialize
          self.cat = Cat.new
        end
      end

      cat_owner = CatOwner.new
      cat_owner.purr  # purr
      cat_owner.meow  # meow
    %br
    %p As you can see, this works pretty much identical to the delegator you'll find in rails.  If we wanted to add prefixing, we could modify the original delegator like so (changes on lines 4, 8, and 10):
    %br
    :coderay
      #!ruby

      def self.delegate(*args)
        options = args.pop
        to = options[:to].to_s
        prefix = options[:prefix] == true

        method_definitions = args.map do |meth|
          string_meth = meth.to_s
          host_meth = prefix ? "\#{to}_\#{string_meth}" : string_meth
          " \
            def \#{host_meth}(*args) \
              \#{to}.\#{string_meth}(*args) \
            end \
          "
        end
        class_eval(method_definitions.join(';'))
      end

app/views/blog/ruby/getters_and_setters.html.haml
.row
  .col-md-12
    %h4 Getters and Setters in Ruby
    %p I wanted to see how a simple method like attr_accessor would be implemented, and here is what I came up with.
    :coderay
      #!ruby

      class Object
        def self.get_n_set(*args)
          code = ''
          args.each do |arg|
            attribute = arg.to_s
            code += %Q{
              def \#{attribute}=(val)
                @\#{attribute} = val
              end

              def \#{attribute}
                @\#{attribute}
              end
            }
          end

          class_eval(code)
        end
      end

      class Example
        get_n_set :name, :age

        def initialize
          self.name = 'JT'
          self.age = 26
        end
      end

      example = Example.new
      puts example.name       # JT
      puts example.age        # 26

app/views/blog/ruby/publisher_subscribe.html.haml
.row
  .col-md-12
    %h4 Observer Pattern
    %p I'm trying to deepen my understanding of how Ruby metaprogramming works, and here is my attempt at a common design pattern.
    :coderay
      #!ruby

      module Publisher
        module ClassMethods
          def publish(*args)
            meth = args.shift
            subscribers.each { |subscriber| subscriber.send(meth, name, *args) }
          end

          def subscribe(subscriber)
            subscribers << subscriber
          end

          def unsubscribe(subscriber)
            subscribers.delete(subscriber)
          end
        end

        def self.included(base)
          base.class_eval do
            include ClassMethods
            send(:attr_accessor, :subscribers, :name)
          end
        end
      end

      module Subscriber
        def subscribe_to(meth, handle_with: :method_missing)
          define_method(meth) { |*args| send(handle_with, *args) }
        end
      end

      module NewspaperSubscriber
        def read_news(newspaper, news)
          puts "\#{newspaper} says: \#{news}"
        end

        def self.included(base)
          base.send :extend, Subscriber
          base.send :subscribe_to, :print_news, handle_with: :read_news
        end
      end

      class Newspaper
        include Publisher

        def initialize(name)
          self.subscribers = []
          self.name = name
        end
      end

      class Person
        include NewspaperSubscriber
      end

      boston_globe = Newspaper.new('Boston Globe')
      hudson_sun = Newspaper.new('Hudson Sun')
      sports_fan = Person.new

      [boston_globe, hudson_sun].each { |newspapah| newspapah.subscribe(sports_fan) }

      boston_globe.publish(:print_news, 'It now costs $300 to see a Sox game.')
      # Boston Globe says: It now costs $300 to see a Sox game!

      hudson_sun.publish(:print_news, 'Drew can play a mean trumpet.')
      # Hudson Sun says: Drew can play a mean trumpet.

app/views/layouts/_header.html.haml
.header
  .pull-left= link_to 'JT BOWLER', root_path
  .pull-right
    %ul.list-inline
      %li= link_to 'About', '/about'
      %li= link_to 'Blog', '/blog'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JT's Personal Site
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %body
      .app-wrapper
        = render 'layouts/header'
        .app-body
          .container-fluid
            = yield

app/views/layouts/blog_layout.html.haml
!!!
%html
  %head
    %title JT's Blog
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .app-wrapper
      = render 'layouts/header'
      .app-body
        .container-fluid.content-area
          - if @return_link
            = link_to 'Back to Blog', blog_index_path
          = yield
          - if @disqus
            .row
              .col-md-12
                :plain
                  <div id="disqus_thread"></div>
                  <script type="text/javascript">
                      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                      var disqus_shortname = 'jtbowler'; // required: replace example with your forum shortname

                      /* * * DON'T EDIT BELOW THIS LINE * * */
                      (function() {
                          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                      })();
                  </script>
                  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    %br
    %br

app/views/pages/about.html.haml
.content-area
  .row
    .col-md-12
      .col-md-6
        %h3 About JT
        %br
          I grew up in Massachusetts with my 6 siblings and 3 cats.  I've always had a lot of hobbies and some of my favorite things to do include:
        %br
        %ul
          %li Programming
          %li Guitar
          %li Piano
          %li Snowboarding
          %li Chess
          %li Drawing
          %li Playing sports
          %li Videogames
          %li Board games
          %li Cigars
          %li Eating popcorn
      .col-md-6
        = image_tag 'about/jt_and_family.jpg', class: 'smaller-image'
        = image_tag 'about/jt_and_jerry.jpg', class: 'smaller-image'

app/views/pages/code.html.haml
.app-body
  .container-fluid.content-area
    .row
      .col-md-12
        %span.disclaimer Disclaimer: &nbsp;
        This code isn't particularly groundbreaking, but I'm keeping a list of code I find thought-provoking or useful.
    .row
      .col-md-12
        %h1 JavaScript Snippets
        %br
        %h4 Delegator Pattern
        :coderay
          #!javascript

          /*
           * At work, we had several objects that received a method call and
           * passed that message to one of the objects it was the owner of.
           * Instead of having these custom methods, I wrote a delegator to
           * write those methods automatically.
           */

          Object.prototype.delegate = function (methods, opts) {
            var self = this;
            if (_.isString(methods)) { methods = [methods]; }

            _.each(methods, function (method) {
              self[method] = function () {
                var receiver = self[opts.to];
                return receiver[method].apply(receiver, arguments);
              };
            });
          };

          // simple usage example...
          var musicBox = {
            hendrix: {
              playGuitar: function () { console.log('twanggggg'); }
            }
          }

          musicBox.delegate('playGuitar', { to: 'Hendrix' });
          musicBox.playGuitar();  //  console:  twanggggg
    %br
    .row
      .col-md-12
        %h1 Ruby Snippets
        %br
        %h4 Observer Pattern
        %p I'm trying to deepen my understanding of how Ruby does it's magic.  This is a [very] basic implementation of the observer pattern.
        :coderay
          #!ruby

          module Publisher
            module ClassMethods
              def publish(*args)
                meth = args.shift
                subscribers.each { |subscriber| subscriber.send(meth, name, *args) }
              end

              def subscribe(subscriber)
                subscribers << subscriber
              end

              def unsubscribe(subscriber)
                subscribers.delete(subscriber)
              end
            end

            def self.included(base)
              base.class_eval do
                include ClassMethods
                send(:attr_accessor, :subscribers, :name)
              end
            end
          end

          module Subscriber
            def subscribe_to(meth, handle_with: :method_missing)
              define_method(meth) { |*args| send(handle_with, *args) }
            end
          end

          module NewspaperSubscriber
            def read_news(newspaper, news)
              puts "\#{newspaper} says: \#{news}"
            end

            def self.included(base)
              base.send :extend, Subscriber
              base.send :subscribe_to, :print_news, handle_with: :read_news
            end
          end

          class Newspaper
            include Publisher

            def initialize(name)
              self.subscribers = []
              self.name = name
            end
          end

          class Person
            include NewspaperSubscriber
          end

          boston_globe = Newspaper.new('Boston Globe')
          hudson_sun = Newspaper.new('Hudson Sun')
          sports_fan = Person.new

          [boston_globe, hudson_sun].each { |newspapah| newspapah.subscribe(sports_fan) }

          boston_globe.publish(:print_news, 'It now costs $300 to see a Sox game.')
          # Boston Globe says: It now costs $300 to see a Sox game!

          hudson_sun.publish(:print_news, 'Drew can play a mean trumpet.')
          # Hudson Sun says: Drew can play a mean trumpet.

app/views/pages/index.html.haml
.main-tagline.text-center
  %h1 JT Bowler
  %br
  %h3
    I enjoy making music and playing with the web.
.cards
  #portfolio.card
    %h4.text-center Portfolio
    %ul
      %li= link_to 'ChalkSchools', 'http://www.chalkschools.com', target: '_blank'
      %li= link_to 'Self Taught Music', 'http://selftaughtmusic.com', target: '_blank'
      %li= link_to 'Binary Tree in JavaScript', 'https://github.com/QuotableWater7/btree', target: '_blank'
      %li= link_to 'Expression Evaluator', 'https://github.com/QuotableWater7/xpression', target: '_blank'
      %li= link_to 'Regex Simulator', 'https://github.com/QuotableWater7/regex_simulator', target: '_blank'
      %br
  #blog.card
    %h4.text-center Blog
    %ul
      %li= link_to 'Delegation (JavaScript)', blog_index_path(lang: 'js', post: 'delegate')
      %li= link_to 'Spies for Testing (JavaScript)', blog_index_path(lang: 'js', post: 'spy')
      %li= link_to 'Functional Programming (JavaScript)', blog_index_path(lang: 'js', post: 'functional_programming')
      %li= link_to 'Delegation (Ruby)', blog_index_path(lang: 'ruby', post: 'delegate')
      %li= link_to 'Publish Subscribe (Ruby)', blog_index_path(lang: 'ruby', post: 'publisher_subscribe')
      %li= link_to 'Getters and Setters (Ruby)', blog_index_path(lang: 'ruby', post: 'getters_and_setters')
    %br
  #music.card
    %h4.text-center My Music
    %ul
      %li= link_to 'SoundCloud', 'http://www.soundcloud.com/bowlah', target: '_blank'
      %li= link_to 'Pure Volume', 'http://www.purevolume.com/jtbowler', target: '_blank'
      %li= link_to 'The Release', 'http://www.thereleasesf.com', target: '_blank'

app/views/pages/portfolio.html.haml
This is my portfolio!